
clean:
	find . -type f -name '*.o' -delete
	find . -type f -name '*.hi' -delete
	find . -type f -name '*.dyn_hi' -delete
	find . -type f -name '*.dyn_o' -delete
	find . -type f -name '*.dyn_hi-boot' -delete
	find . -type f -name '*.dyn_o-boot' -delete
	find . -type f -name '*.p_o' -delete
	find . -type f -name '*.hi-boot' -delete
	find . -type f -name '*.p_o-boot' -delete
	find . -type f -name '*.o-boot' -delete